config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: %i[new create destroy]
    end
  end

  scope module: :apps do
    resources :accounts, only: [:show] do
      resources :follows, only: [:create]
      resources :unfollows, only: [:create]
    end
    resource :timeline, only: [:show]
  end
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  board_id    :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :board
  has_one_attached :eyecatch
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @board = Board.find(params[:board_id])
    @tasks = @board.tasks
  end

  def show
    @task = Task.find(params[:id])
    @comments = @task.comments
  end

  def new
    # user_idをログインユーザーのidとしたtaskインスタンスを生成
    @task = current_user.tasks.build
    # taskの不足しているboard_idを下記で指定
    @board = Board.find(params[:board_id])
    @task.board_id = @board.id
  end

  def create
    # user_idをログインユーザーのidとしたtaskインスタンスを生成
    @task = current_user.tasks.build(task_params)
    @board = Board.find(params[:board_id])
    # taskのboard_idを下記で指定
    # @board = current_user.boards.find(params[:board_id])
    # @task.board_id = @board.id
    if @task.save
      redirect_to board_tasks_path, notice: '保存出来ました！'
    else
      flash.now[:error] = '保存に失敗しました！'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
    @board = Board.find(params[:board_id])
  end

  def update
    @task = current_user.tasks.find(params[:id])
    # @board = current_user.boards.find(params[:board_id])
    # @task.board_id = @board.id
    if @task.update(task_params)
      redirect_to board_tasks_path, notice: '更新出来ました！'
    else
      flash.now[:error] = '更新に失敗しました！'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    board = Board.find(params[:board_id])
    @task.board_id = board.id
    @task.destroy!
    redirect_to board_tasks_path, notice: '削除出来ました！'
  end

  # create,editでの変更内容を制御
  private

  def task_params
    params.require(:task).permit(:name, :description, :eyecatch).merge(board_id: params[:board_id])
  end
end

app/views/tasks/_form.html.haml
-# エラーメッセージ
%ul
  - task.errors.full_messages.each do |message|
    %li= message
-# フォーム
= form_with model:[board, task], local: true do |f|
  .field.form__item
    = f.label :eyecatch, 'Eyecatch'
    %br
    = f.file_field :eyecatch, class: 'form__eyecatch'
  .field.form__item
    = f.label :name, 'Name',class: 'form__title'
    %br
    = f.text_field :name, class: 'form__text'
  .field.form__item
    = f.label :description, 'Description',class: 'form__title'
    %br
    = f.text_area :description, class: 'form__text form__text-ara'
  .form__btn
    = f.submit 'Submit', class: 'form__btn-text'

app/views/tasks/edit.html.haml
.container
  %h2 Edit Card
  = render "form", task: @task, board: @board

app/views/tasks/index.html.haml
.container
  %h2
    = @board.name
  .post
    - @tasks.each do |task|
      = link_to(board_task_path(id: task.id)) do
        .post__item
          - if task.eyecatch.present?
            .post__img-box
              = image_tag task.eyecatch, class: 'post__img'
          %h3.post__title
            = task.name
          %p.post__text
            = task.description
          = image_tag 'avatar-2', alt: 'tasksの投稿者画像', class: 'post__image'
  -if user_signed_in?
    .post
      = link_to('+ Add new card', new_board_task_path, class: 'post__new-link')

app/views/tasks/new.html.haml
.container
  %h2 New Card
  = render "form",board: @board, task: @task

app/views/tasks/show.html.haml
.container
  .post
    .post__head
      %h2
        = @task.name
      -if user_signed_in? && current_user.tasks.exists?(id: @task)
        .dropdown.post__dropdown.post__dropdown--title
          %button.three-dot-leader
            %span.dot
              .dropdown-content
                = link_to 'Edit', edit_board_task_path(id: @task.id)
                = link_to 'Delete', board_task_path(id: @task.id), data: { turbo_method: "delete", turbo_confirm: '本当に削除しても宜しいですか？' }
    - if @task.eyecatch.present?
      .post__img-box
        = image_tag @task.eyecatch, class: 'post__img'
    .post__item
      %p.post__text.post__text--first
        = @task.description
  .post
    %h2 Comment
    -@comments.each do |comment|
      %p.post__text
        = comment.description
  -if user_signed_in?
    .post
      = link_to('+ Add new comment', new_board_task_comment_path(task_id: @task.id), class: 'post__new-link')