config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: %i[new create destroy]
    end
  end

  scope module: :apps do
    resources :accounts, only: [:show] do
      resources :follows, only: [:create]
      resources :unfollows, only: [:create]
    end
    resource :timeline, only: [:show]
  end
end

app/views/commons/_boards.html.haml
.post
  - boards.each do |board|
    = link_to(board_tasks_path(board_id: board.id)) do
      .post__item
        %h3.post__title
          = board.name
        %p.post__text
          = board.description
        = link_to account_path(board.user) do
          = image_tag 'avatar-2', alt: 'boardsの投稿者画像', class: 'post__image'
        %p.post__text
          = board.display_created_at
        -if user_signed_in? && current_user. has_written?(board)
          .dropdown.post__dropdown
            %button.three-dot-leader
              %span.dot
                .dropdown-content
                  = link_to 'Edit', edit_board_path(id: board.id)
                  = link_to 'Delete', board_path(id: board.id), data: { turbo_method: "delete", turbo_confirm: '本当に削除しても宜しいですか？' }
-if user_signed_in?
  .post
    = link_to('+ Add new board', new_board_path, class: 'post__new-link')