config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: %i[new create destroy]
    end
  end

  scope module: :apps do
    resources :accounts, only: [:show] do
      resources :follows, only: [:create]
      resources :unfollows, only: [:create]
    end
    resource :timeline, only: [:show]
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todo
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %header.header
      %h1.header__title
        = link_to('Boards', root_path)
      - if user_signed_in?
        .dropdown
          = image_tag 'default-avatar', alt: 'サンプル画像', class:"header__img"
          .dropdown-content
            = link_to 'timeline', timeline_path
            = link_to 'logout', destroy_user_session_path, data: { turbo_method: :delete }

      - else
        = link_to 'login', new_user_session_path, class: 'header__btn'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield